/**
 * exemplo de uso de condicionais
 */
let idade = 18;
//usando if(se)
if (idade>=18){
    console.log('voce pode dirigir');
} else if (idade>= 16) {
    console.log('voce esta quase podendo dirigir');
} else {
    console.log('voce nao pode');
}
/**
 * operadores relacionais
 * > maior que 
 * < menor que
 * = igual a
 * != diferente
 * >= maior ou igual
 * <= menor ou igual
 * 
 * exmplos com texto
 * 'Ana' > 'ana' => falso
 * 
 * operdores logicos
 * && operador AND => idade >=18 && idade <= 60         => verdadeiro para idades entre 18 e 60
 * || operador OR
 * !  operador NOT
 * 
 */